---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"] 

- hosts: web_servers
  become: true
  tasks: