- name: install nginx package
  tags: nginx,ubuntu
  package:
    name: 
      - "{{ nginx_package_name }}"
    state: latest

- name: start and enable nginx
  tags: nginx
  service:
    name: "{{ nginx_service }}"
    state: started
    enabled: yes

- name: allow Nginx Full through firewall
  tags: nginx
  ufw:
    rule: allow
    name: Nginx Full
